export const PERMISSIONS = {
  dashboardView: "dashboard:view",
  cmsSiteList: "cms:site:list",
  cmsSiteUpdate: "cms:site:update",
  cmsMediaList: "cms:media:list",
  cmsMediaUpload: "cms:media:upload",
  cmsMediaUpdate: "cms:media:update",
  cmsMediaDelete: "cms:media:delete",
  userList: "system:user:list",
  userCreate: "system:user:create",
  userUpdate: "system:user:update",
  userDelete: "system:user:delete",
  roleList: "system:role:list",
  roleCreate: "system:role:create",
  roleUpdate: "system:role:update",
  roleDelete: "system:role:delete",
  roleGrant: "system:role:grant",
  menuList: "system:menu:list",
  menuCreate: "system:menu:create",
  menuUpdate: "system:menu:update",
  menuDelete: "system:menu:delete",
  organizationList: "system:organization:list",
  organizationCreate: "system:organization:create",
  organizationUpdate: "system:organization:update",
  organizationDelete: "system:organization:delete",
  operationLogList: "system:operation-log:list",
  loginLogList: "system:login-log:list",
  profileUpdate: "account:profile:update",
  passwordUpdate: "account:password:update",
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PERMISSION_NAMES: Record<PermissionCode, string> = {
  [PERMISSIONS.dashboardView]: "查看数据概览",
  [PERMISSIONS.cmsSiteList]: "查看站点设置",
  [PERMISSIONS.cmsSiteUpdate]: "修改站点设置",
  [PERMISSIONS.cmsMediaList]: "查看媒体库",
  [PERMISSIONS.cmsMediaUpload]: "上传媒体文件",
  [PERMISSIONS.cmsMediaUpdate]: "修改媒体信息",
  [PERMISSIONS.cmsMediaDelete]: "删除媒体文件",
  [PERMISSIONS.userList]: "查看用户列表",
  [PERMISSIONS.userCreate]: "新增用户",
  [PERMISSIONS.userUpdate]: "修改用户",
  [PERMISSIONS.userDelete]: "删除用户",
  [PERMISSIONS.roleList]: "查看角色列表",
  [PERMISSIONS.roleCreate]: "新增角色",
  [PERMISSIONS.roleUpdate]: "修改角色",
  [PERMISSIONS.roleDelete]: "删除角色",
  [PERMISSIONS.roleGrant]: "分配角色权限",
  [PERMISSIONS.menuList]: "查看菜单列表",
  [PERMISSIONS.menuCreate]: "新增菜单项",
  [PERMISSIONS.menuUpdate]: "修改菜单项",
  [PERMISSIONS.menuDelete]: "删除菜单项",
  [PERMISSIONS.organizationList]: "查看组织列表",
  [PERMISSIONS.organizationCreate]: "新增组织",
  [PERMISSIONS.organizationUpdate]: "修改组织",
  [PERMISSIONS.organizationDelete]: "删除组织",
  [PERMISSIONS.operationLogList]: "查看操作日志",
  [PERMISSIONS.loginLogList]: "查看登录日志",
  [PERMISSIONS.profileUpdate]: "修改个人资料",
  [PERMISSIONS.passwordUpdate]: "修改登录密码",
};
